### ISSUE TITLE
cool project man

### ISSUE THREAD

**Issue by DanielCawley** [danielfostiak/A-Level-NEA-project#1]
hey im a year 11 just checking out a level cs projects to see their complexity, this seems pretty cool, did you know any react/next in year 11 or did you learn all of this at school, ive done a react udemy course before but im wondering if i should refresh my knowledge on it for the a level

**Comment by DanielCawley** [comment]
this may be just some random guessing by me, but did you complete the Maximilian Schwarzmüller academind udemy course, your code just looks really similar to the style he coded in for that course haha

**Comment by danielfostiak** [comment]
Hey Dan, (same name, nice).
I have been coding in react and next for a few years now on and off. I remember when I started I used that udemy course but didn't like it very much so barely completed any of it. I would say the best way to go about learning these frameworks is 1. Get very very good at JS, most important thing ever. 2. Learn by doing projects, use the docs and search stuff up when you are stuck, this is a useful skill rather than just following someone else code. After this you should be comfortable coding in react. Also, I have since changed my A level NEA project to my latest repo, WordLINK. It's also a NextJS app but just something I thought was more fun and also would prefer to write about. If you have any questions, feel free to email me (email is on my profile). For now I am gonna close this issue. Thanks man.
